export const LOAD_CONVERSATIONS_PROGRESS = 'LOAD_CONVERSATIONS_PROGRESS'
export const LOAD_CONVERSATIONS_SUCCESS = 'LOAD_CONVERSATIONS_SUCCESS'
export const LOAD_CONVERSATIONS_ERROR = 'LOAD_CONVERSATIONS_ERROR'
export const CLEAR_DATA = 'CLEAR_CONVERSATIONS_DATA'
