export const SIGN_IN_LOCAL_SUCCESS = 'SIGN_IN_LOCAL_SUCCESS'
export const SIGN_IN_LOCAL_ERROR = 'SIGN_IN_LOCAL_ERROR'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
