export const START_UPDATING_PROFILE = 'START_UPDATING_PROFILE'
export const FINISH_UPDATING_PROFILE = 'FINISH_UPDATING_PROFILE'
export const CANCEL_UPDATING_PROFILE = 'CANCEL_UPDATING_PROFILE'

export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS'
export const SAVE_PROFILE_ERROR = 'SAVE_PROFILE_ERROR'
export const PROFILE_START_LOCAL_LOADING = 'PROFILE_START_LOCAL_LOADING'
